### ISSUE TITLE
Couldn't find index page for 'mirnylib' 

### ISSUE THREAD

**Issue by johnire80** [Phlya/coolpuppy#1]
I'm having difficulty building coolpuppy - a pip install fails and by hand I get,

$ python setup.py install
<CUT>
Searching for mirnylib
Reading https://pypi.org/simple/mirnylib/
Couldn't find index page for 'mirnylib' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for mirnylib
error: Could not find suitable distribution for Requirement.parse('mirnylib')

**Comment by Phlya** [comment]
Hi John,

mirnylib is not on PyPI AFAIK, please follow the procedure here: https://bitbucket.org/mirnylab/mirnylib
`pip install https://bitbucket.org/mirnylab/mirnylib/get/tip.tar.gz`

Sorry, should mention this in readme!

**Comment by johnire80** [comment]
Installed!   But required,
pip install Cython
pip install natsort
pip install https://bitbucket.org/mirnylab/mirnylib/get/tip.tar.gz
pip install coolpuppy_

**Comment by Phlya** [comment]
Right, thanks! Not sure why `natsort` wouldn't be just installed as a dependency... And Cython must be  `mirnylib` dependency, not mentioned in their `setup.py`.
