### ISSUE TITLE
Hi-C interaction enrichment around ChIP-seq peaks 

### ISSUE THREAD

**Issue by Kurotakid** [Phlya/coolpuppy#10]
Hi,
I want to analyze the role of a transcription factor (TF) in 3D chromatin architecture establishment.
I have ChIP-seq peak bed files of the TF and Hi-C data (.cool) in WT and TF KO cells. If I analyze Hi-C interaction enrichment around ChIP-seq peaks, how should I run the coolpuppy tool? I want to know typical analysis parameters and commands of the coolpuppy for Hi-C interaction around TF binding sites.
Daisuke

**Comment by Phlya** [comment]
Hi, just this should do the trick:

`coolpup.py <cool_file> <bed_file> `

Additionally, if you have calculated expected values per diagonal (`cooltools compute-expected`), you can use it for faster normalization by adding `--expected <expected_file>`. If you have multiple cores available, you can speed up the analysis by adding `--n_proc <num_cores>`. Let me know if you have any more questions.

**Comment by Kurotakid** [comment]
Thank you for your quick reply. 
I received an error message although  I run the command you provided as follows:

[kurotaki ~/HiC/coolpuppy-master/docs]$coolpup.py WT_10000.cool TF.bed               Namespace(anchor=None, baselist='TF.bed', bed2=None, bed2_ordered=True, bed_ordered=True, by_window=False, coolfile='WT_10000.cool', coverage_norm=False, excl_chrs='chrY,chrM', expected=None, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='.', outname='auto', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, subset=0, unbalanced=False, weight_name='weight')
Note: detected 72 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
Note: NumExpr detected 72 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/kurotaki/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/kurotaki/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/coolpuppy/coolpup.py", line 378, in pileups
    data = get_data(chrom, c, balance, local)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/coolpuppy/coolpup.py", line 257, in get_data
    data = c.matrix(sparse=True, balance=balance).fetch(chrom)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/cooler/core.py", line 570, in fetch
    return self._slice(self.field, i0, i1, j0, j1)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/cooler/api.py", line 342, in _slice
    self._is_symm_upper)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/cooler/api.py", line 631, in matrix
    "calculate balancing weights or set balance=False.")
ValueError: No column 'bins/weight' found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kurotaki/miniconda3/bin/coolpup.py", line 10, in <module>
    sys.exit(main())
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/coolpuppy/__main__.py", line 406, in main
    rescale_size=args.rescale_size)
  File "/home/kurotaki/miniconda3/lib/python3.6/site-packages/coolpuppy/coolpup.py", line 478, in pileupsWithControl
    loops, ns, cov_starts, cov_ends = list(zip(*p.map(f, chrommids)))
  File "/home/kurotaki/miniconda3/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kurotaki/miniconda3/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
ValueError: No column 'bins/weight' found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.

How can I overcome this problem?
I would appreciate it if you would give me some advice.
Daisuke

**Comment by Phlya** [comment]
Your data isn't balanced. If that is on purpose, add `--unbalanced` to the coolpup.py command (and I recommend `--coverage_norm` too), however most likely you want to balance your data using `cooler balance`.

Also, sorry, I misread your original message. If you are interested in local interactions around the binding site rather than interactions between binding sites, you need to add `--local` argument.

**Comment by Kurotakid** [comment]
I was able to have a good result because of your instructions. Thank you!
Daisuke

**Comment by sachingadakh** [comment]
> Your data isn't balanced. If that is on purpose, add `--unbalanced` to the coolpup.py command (and I recommend `--coverage_norm` too), however most likely you want to balance your data using `cooler balance`.
> 
> Also, sorry, I misread your original message. If you are interested in local interactions around the binding site rather than interactions between binding sites, you need to add `--local` argument.

Hello,
 I received the error such as "coolpup.py: error: unrecognized arguments: --unbalanced", when I use the --unbalanced parameter in my following command
coolpup.py 4DNFIIMZB6Y910kbdekker.cool H1_hic_dekkerTADs_chr18.bed --local --unbalanced --coverage_norm

**Comment by sachingadakh** [comment]
> Can you try using `--clr_weight_name ""` instead?

Thank you for quick reply but now getting new error such as "coolpup.py: error: argument --clr_weight_name/--weight_name: expected one argument", for the following command:
coolpup.py 4DNFIIMZB6Y910kbdekker.cool H1_hic_dekkerTADs_chr18.bed --local --unbalanced --coverage_norm 
--clr_weight_name

**Comment by sachingadakh** [comment]
yes added the "". It is processing

**Comment by sachingadakh** [comment]
I got the output .clpy file. I will visualize it and keep you updated. Thank you very much

**Comment by Phlya** [comment]
Great!

**Comment by Phlya** [comment]
FYI I just pushed a small update to the master branch where you don't need to use "". But also it requires latest version of cooltools.

**Comment by jtxyz16** [comment]
Hi, I got this error on mine:

/home/gridsan/jteves/miniconda3/bin/coolpup.py:466: UserWarning: Found inter-chromosomal loci pairs, discarding them
  warnings.warn("Found inter-chromosomal loci pairs, discarding them")
Namespace(coolfile='/home/gridsan/jteves/galloway_shared/data/NGS_DATA/HiC/jobs/DDRRbulk.cool', baselist='/home/gridsan/jteves/galloway_shared/data/NGS_DATA/HiC/coolpuppy/MEFoveriMN.bed', pad=100, minshift=100000, maxshift=1000000, nshifts=10, mindist=None, maxdist=None, excl_chrs='chrY,chrM', incl_chrs='all', anchor=None, by_window=False, save_all=False, local=False, rescale=False, rescale_pad=1.0, size=90, subset=0, unbalanced=True, coverage_norm=True, n_proc=1, outdir='/home/gridsan/jteves/galloway_shared/data/NGS_DATA/HiC/cooler_test', outname='auto')
Traceback (most recent call last):
  File "/home/gridsan/jteves/miniconda3/bin/coolpup.py", line 525, in <module>
    loop = pileupsWithControl(mids=mids, filename=args.coolfile,
  File "/home/gridsan/jteves/miniconda3/bin/coolpup.py", line 195, in pileupsWithControl
    loop = np.average(loops, axis=0, weights=ns) #Weights from how many windows we actually used
  File "<__array_function__ internals>", line 180, in average
  File "/home/gridsan/jteves/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 547, in average
    raise ZeroDivisionError(
ZeroDivisionError: Weights sum to zero, can't be normalized

**Comment by Phlya** [comment]
@jtxyz16 first of all, in the future, please create a new issue to report a problem.

Secondly, I think your coolpuppy is an old version, I would recommend updating to the latest release. But it appears that your issue is coming from having no usable data for some reason.
