### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by docdot** [Phlya/coolpuppy#14]
Hi,

Thanks for this tool. It appears to be exactly I was looking for.
However, I am facing an error during installation.
Using:

```
sudo -H pip install coolpuppy
or
sudo -H pip install https://github.com/Phlya/coolpuppy/archive/master.zip
or
sudo python -m pip install coolpuppy
or
sudo python -m pip install https://github.com/Phlya/coolpuppy/archive/master.zip
```
I have the same error:

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YjxNQc/coolpuppy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YjxNQc/coolpuppy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-YjxNQc/coolpuppy/pip-egg-info
         cwd: /tmp/pip-install-YjxNQc/coolpuppy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-YjxNQc/coolpuppy/setup.py", line 5, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I had no issues installing cooltools. 
It would be great to receive any input on how to fix this...

Thanks,

**Comment by Phlya** [comment]
Hi, are you using Python 2?

**Comment by docdot** [comment]
Yes... 
Please tell me that I can still use Python 2.7..

**Comment by Phlya** [comment]
It is not tested on Python 2.X, and so these kind of things creep in and make it break - Python 2 stops getting support in just over a month, really time to upgade...

If you really want to use it on Python 2, feel free to fix it and submit a PR, the solution is here:
https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2

But I can't promise this is the only problem you'll encounter...

**Comment by Phlya** [comment]
I.e. I don't want to invest my resources in supporting Python 2, but happy to merge PRs if you prepare them and they don't affect results/performance on Python 3.

**Comment by docdot** [comment]
Thanks.. 
I will try both options: migrating to Python 3 and in the meantime have this fixed just to run a test.
Thanks for your prompt reply!
