### ISSUE TITLE
Error on edge of chromosome # RuntimeError: vector::_M_fill_insert

### ISSUE THREAD

**Issue by docdot** [Phlya/coolpuppy#15]
Hi,

I have recently started using coolpuppy tools and it is presenting the following error:

command:
`coolpup.py '/media/Data/Data/HiC/EtOH_500000.cool' '/media/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed' --nshifts 10 --unbalanced --coverage_norm --mindist 100000 --outname Ctrl_loop.txt`

output: 
```
Namespace(anchor=None, baselist='/media/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed', bed2=None, bed2_ordered=True, bed_ordered=True, by_window=False, coolfile='/media/Data/Data/HiC/EtOH_500000.cool', coverage_norm=True, excl_chrs='chrY,chrM', expected=None, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=100000, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='.', outname='Ctrl_loop.txt', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=True, weight_name='weight')
Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
chr1: 102378
chr2: 112575
chr3: 73920
chr4: 69006
chr5: 61425
chr6: 55278
chr7: 48205
chr8: 40755
chr9: 29161
chr10: 34716
chr11: 33670
chr12: 33930
chr13: 17578
chr14: 15400
chr15: 13695
chr16: 12561
chr17: 12403
chr18: 10585
chr19: 6216
chr20: 7260
chr21: 2628
chr22: 2485
chrX: 44551
Total number of piled up windows: 840381
chr13: 175780
chr14: 154000
chr15: 136950
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 440, in pileups
    anchor=anchor)
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 297, in _do_pileups
    lo_right:hi_right].toarray()
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/_index.py", line 51, in __getitem__
    return self._get_sliceXslice(row, col)
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py", line 652, in _get_sliceXslice
    return self._get_submatrix(major, minor, copy=True)
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py", line 789, in _get_submatrix
    M, N, self.indptr, self.indices, self.data, i0, i1, j0, j1)
RuntimeError: vector::_M_fill_insert
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/__main__.py", line 416, in main
    seed=args.seed)
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 509, in pileupsWithControl
    ctrls, ns, cov_starts, cov_ends = list(zip(*p.map(f, chrommids)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: vector::_M_fill_insert

```

Any thoughts that can help me to sort this out? 

Thank you.

**Comment by Phlya** [comment]
Hi. Wow, I have never seen this error. There aren't really any references to this error on Google, as far as I can tell...

This _shouldn't_ cause this, but is it possible you have some regions very close to the edge of a chromosome? What if you remove them?

Does this happen only with this particular set of regions, or this cool file, or these settings?

It seems it only happens at the stage of random shift controls, can you try using expected instead?

**Comment by docdot** [comment]
Hi,

Thanks for your prompt reply. Hopefully, we will figure this out.
About your questions:

Q:"This shouldn't cause this, but is it possible you have some regions very close to the edge of a chromosome? What if you remove them?"
A: No change

Q:"Does this happen only with this particular set of regions, or this cool file, or these settings?"
A: No. It happens with a second file I tried, even using different settings and combinations. 
These files were processed with HiC-Pro to build an 500000 bp matrix and transformed to .cool format (using this tool https://github.com/nservant/HiC-Pro/blob/master/doc/UTILS.md#hicpro2higlasssh-or-how-can-i-load-my-hic-pro-output-into-the-higlass-visualization-tool- ). cooltoos work well with these files, so I would discard the problem is the file or conversion per se.

Q: "It seems it only happens at the stage of random shift controls, can you try using expected instead?"
A: I did and it kind of work - but I'm not sure is giving the correct output.

I ran the following commands:
```
$cooltools compute-expected '/media/Data/Data/HiC/EtOH_500000.cool' > expected.txt
$coolpup.py '/media/test/Data/Data/HiC/SHEP_G1_EtOH_500000.cool' '/media/test/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed' --expected expected.txt --unbalanced --coverage_norm --mindist 100000 --outname GO.txt --n_proc 100
```
Output: 
```
Namespace(anchor=None, baselist='/media/test/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed', bed2=None, bed2_ordered=True, bed_ordered=True, by_window=False, coolfile='/media/test/Data/Data/HiC/EtOH_500000.cool', coverage_norm=True, excl_chrs='chrY,chrM', expected='expected.txt', incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=100000, minshift=100000, minsize=None, n_proc=100, nshifts=10, outdir='.', outname='GO.txt', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=True, weight_name='weight')
With specified expected will not use controls
Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
chr22: 2485
chr21: 2628
chr19: 6216
chr20: 7260
chr16: 12561
chr18: 10585
chr17: 12403
chr15: 13695
chr14: 15400
chr13: 17578
chr9: 29161
chr12: 33930
chr11: 33670
chr10: 34716
chr8: 40755
chrX: 44551
chr7: 48205
chr6: 55278
chr5: 61425
chr4: 69006
chr3: 73920
chr2: 112575
chr1: 102378
Total number of piled up windows: 840381
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
Doing expected
chr22: 2485
chr21: 2628
chr19: 6216
chr20: 7260
chr16: 12561
chr18: 10585
chr15: 13695
chr17: 12403
chr13: 17578
chr14: 15400
chr9: 29161
chr10: 34716
chr12: 33930
chr11: 33670
chr8: 40755
chrX: 44551
chr6: 55278
chr7: 48205
chr5: 61425
chr4: 69006
chr3: 73920
chr1: 102378
chr2: 112575
Saved output to /home/test/Desktop/GO.txt
```
/home/test/Desktop/GO.txt file:
`4.279044171596997330e+03`

Running plotpup.py with this file:
```
$ plotpup.py GO.txt --output gene.png
Traceback (most recent call last):
  File "/usr/local/bin/plotpup.py", line 8, in <module>
    sys.exit(plotpuppy())
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/__main__.py", line 597, in plotpuppy
    extent=(0, 1, 0, 1))
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cbook/deprecation.py", line 369, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_axes.py", line 5671, in imshow
    im.set_data(X)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 690, in set_data
    .format(self._A.shape))
TypeError: Invalid shape () for image data
```
I trying to pileup this HiC data set with refseq genes bed files. I also tried with bedpe file (using TSS and TES as each end). Could be something related to the fact that genes lengths are way smaller than the Hi-C resolution I'm using? 

If not, any other ideas that can help me?

Thank you.

**Comment by Phlya** [comment]
Yes! That's really low resolution, either try higher resolution (even if
you have very low sequencing depth, pile-ups will probably work) or
increase pad to include a few bins on each side, e.g. 1Mb at least.

**Comment by docdot** [comment]
Hi,

I generated a 2500 and a 10000 bp resolution matrix, converted to .cool, and used `cooler balance`. 
I ran again coolpup.py using these new matrices plus increasing or not the pads. And I tried different options as well (including with --expected).

Output for both matrices: 
```
$ coolpup.py '/home/test/Desktop/G1_EtOH_tools.cool' '/media/test/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed' --n_proc 100 --nshifts 10 --unbalanced --coverage_norm --outname ok.txt
Namespace(anchor=None, baselist='/media/test/Data/Genomes_ref/genes_files/RefSeq_ensembl_genes.bed', bed2=None, bed2_ordered=True, bed_ordered=True, by_window=False, coolfile='/home/test/Desktop/G1_EtOH_tools.cool', coverage_norm=True, excl_chrs='chrY,chrM', expected=None, incl_chrs='all', local=False, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=100, nshifts=10, outdir='.', outname='ok.txt', pad=100, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=True, weight_name='weight')
Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
chr21: 938868
chr13: 2260090
chr22: 3085303
chrX: 6879596
chr14: 8955435
chr15: 9936805
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 440, in pileups
    anchor=anchor)
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 297, in _do_pileups
    lo_right:hi_right].toarray()
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/_index.py", line 51, in __getitem__
    return self._get_sliceXslice(row, col)
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py", line 652, in _get_sliceXslice
    return self._get_submatrix(major, minor, copy=True)
  File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py", line 789, in _get_submatrix
    M, N, self.indptr, self.indices, self.data, i0, i1, j0, j1)
RuntimeError: vector::_M_fill_insert
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/coolpup.py", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/__main__.py", line 416, in main
    seed=args.seed)
  File "/usr/local/lib/python3.6/dist-packages/coolpuppy/coolpup.py", line 486, in pileupsWithControl
    loops, ns, cov_starts, cov_ends = list(zip(*p.map(f, chrommids)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: vector::_M_fill_insert
```
Any further ideas?

Thanks

**Comment by docdot** [comment]
Do you prefer that I sent you the file?

**Comment by Phlya** [comment]
That's very strange. If you can share the file with me it might help...

**Comment by Phlya** [comment]
Also, you are using 100 cores, but coolpuppy only parallelizes with a core per chromosome, what if you set it a value smaller than number of chromosomes?

**Comment by docdot** [comment]
Thanks for your feedback, sorry for the delay as I did not have access over the weekend.
I sent you the files over email as I can't make it public.
At this point, I'm able to 1- reproduce your example using your example files and 2- use my .cool or .mcool files with the TAD .bed files from your example. Everything else fails.
Meaning there is something weird going with my .bed or .bedpe files (I also sent you).
Files per se appear to be fine: /t limited with chr.  Also, I can use other tools with them.
I think can be something related to the resolution (one is TSS to TES). However, even if I use TAD .bed based on my own data it doesn't work..
It would be great if you could have a look into it. I hope may also help people in the future to deal with this issue.
Thanks.

**Comment by Phlya** [comment]
I have a feeling something must have changed in sparse indexing, because the problem was indeed in regions on the edge of the chromosome. Unless I am confused, it used to just return an array of smaller size/shape, and now it errors with this obscure exception.

I added a temporary fix to simply ignore regions not fully within the chromosome bounds (instead of filling areas outside with NaNs), and this avoids this problem. I would like to re-write this part (pulling out mini rectangles) using cooltools.snipping, and then this should be solved properly (although I think there these regions are already ignored/fully filled with NaNs).

By the way, for quicker testing you can use `coolpup.py EtOH_tools.cool RefSeq_genes_sorted.bed --unbalanced --coverage_norm --subset 500 --seed 0 --incl_chrs chrX`.

Please let me know if the new version on GitHub solves your problem!

**Comment by docdot** [comment]
It is working now! Many thanks!
I just have a few questions about it:

Why doesn't work with --expected and only with  --unbalanced --coverage_norm? Has it to do with sequencing depth?

Is there any reason you may think for the edge of the chromosomes present this issue? Artefact during some step?

Even using your command  I can't have the "five"-square shape typical of TADs (as shown here https://github.com/Phlya/coolpuppy/blob/master/docs/Examples.ipynb). Is this a .cool resolution issue (should I decrease resolution to 25-50kb) or is this --local --rescale related?

Should I change the name of this report to help others to find? If yes, I will close this report after changing it.

Many thanks again for your help. I deeply appreciated.

**Comment by Phlya** [comment]
`--expected` and '--unbalanced --coverage_norm` are different things. Expected is about how to normalize the decay of contact frequency with distance (alternative is random shifts), and unbalnaced/coverage normalization is about whether to use iteratively corrected data and pseudo-iterative correction during pileup creation, that's only useful for very low sequenced data when balancing doesn't converge, or single cell data where its assumptions are invalid.

Edges present the issue because either due to padding, or when creating random shifts, the region that we need to get is partly outside the chromosome coordinates, e.g. negative coordinates.

What coordinates are you using for TADs? The ones in this repository are for mm9, and you have human data.

Yeah, would be good to rename it to something about edge of chromosome issue.

**Comment by docdot** [comment]
Thanks for your reply and for clarifying some questions.

About your question on TAD the coordinates, I'm using the output of `cooltools diamond-insulation`

Closing here the issue. Thanks again! Very helpful!

**Comment by Phlya** [comment]
You probably need deeper data to annotate TADs... Try using some published data and the do a pileup.
