### ISSUE TITLE
minimal number of loops for pile-up analysis

### ISSUE THREAD

**Issue by musiccccc** [Phlya/coolpuppy#21]
Hi,
When I do the pile-up analysis on a loop file (about 177 loops), coolpuppy reports the following error:
"ValueError: No chromosomes are in common between the coordinate file/anchor and the cooler file. Are they in the same format, e.g. starting with "chr"? Alternatively, all regions might have been filtered by distance/size filters." 
However, when I apply same parameters to another loop file with same format (about 509 loops), it's ok. 
So I am wondering what's the minimal number of loops for pile-up analysis?
Looking forward to your helpful reply.
Qiang

**Comment by Phlya** [comment]
Hi Qiang,

That's strange, this shouldn't happen! Could you share some more details? What do your files look like? Do you mind sharing them?

**Comment by musiccccc** [comment]
Hi Phlya,

Thanks for your kindly reply.
Here is my input loop file (bedpe):
1       28960000        28970000        1       29100000        29110000
2       171780000       171790000       2       172010000       172020000
2       196520000       196530000       2       196930000       196940000
2       219120000       219130000       2       219260000       219270000
2       231910000       231920000       2       232310000       232320000
2       242600000       242610000       2       242820000       242830000
3       11680000        11690000        3       11880000        11890000
3       12520000        12530000        3       12700000        12710000
3       13690000        13700000        3       13930000        13940000
3       13930000        13940000        3       14160000        14170000
 
And here is code for pile-up analysis:
coolpup.py hic.cool input_loop.bed --nshifts 10 --unbalanced --coverage_norm --mindist 100000 --outname output.txt

Best,
Qiang

**Comment by Phlya** [comment]
Is it tab delimited? What are the chromosomes stored in the cooler you are working with?

**Comment by musiccccc** [comment]
Yes, it's tab delimited. 
I think chromosome is not the point. Because another loop file has same format as previous one, and it uses the same cooler for pipe-up analysis.

**Comment by musiccccc** [comment]
By the way, all the loop file with row number around or less than 200 will raise this error.

**Comment by Phlya** [comment]
OK, it shouldn't happen, and works for me with the latest version for any small number of loops using the latest version from GitHub - even with 20 loops, and even when no loops pass the distance filters, so I get an output with all zeros. Can you try the latest version please? This could have cause problems if some chromosomes had no loops in them, but it would have raised a different error...

**Comment by musiccccc** [comment]
OK, I will try the latest version of coolpuppy. Thanks for your kindly help!

**Comment by Phlya** [comment]
How are you getting on? Did the new version fix your issue?

**Comment by musiccccc** [comment]
Sorry for my later reply. The new version solved my problem. Thank you!
