### ISSUE TITLE
Local pileup gives "NoneType" error for some but not all input BED files

### ISSUE THREAD

**Issue by tanlongzhi** [Phlya/coolpuppy#23]
Hi,

I love using coolpup.py, but recently encountered a problem: When I tried to run "--local" on insulation boundaries (supplied as BED files), it gives an error "TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'" for some but not all of my BED files.

Strangely, it works on some BED files but not others. Below are 3 example files that either work or not:
- [original_fail.bed.txt](https://github.com/Phlya/coolpuppy/files/5110334/original_fail.bed.txt)
- [test1_good.bed.txt](https://github.com/Phlya/coolpuppy/files/5110335/test1_good.bed.txt)
- [test2_fail.bed.txt](https://github.com/Phlya/coolpuppy/files/5110336/test2_fail.bed.txt)

In the above case, the whole file failed but certain subsets worked. For some other case (not shown), the whole file worked but certain subsets failed.

Would you mind helping me fix this problem? Thank you very much in advance.

FYI below is the full command the error message, in case it helps your diagnosis:
```sh
(py3) plenty:aggregate_data tanlongzhi$ coolpup.py aggregated_data.clusters_neonatal_neurons.contacts.mcool::/resolutions/16000 test2_fail.bed --local
Namespace(anchor=None, baselist='test2_fail.bed', bed2=None, bed2_ordered=True, by_window=False, coolfile='aggregated_data.clusters_neonatal_neurons.contacts.mcool::/resolutions/16000', coverage_norm=False, excl_chrs='chrY,chrM', expected=None, ignore_diags=2, incl_chrs='all', local=True, logLevel='INFO', maxdist=None, maxshift=1000000, maxsize=None, mindist=None, minshift=100000, minsize=None, n_proc=1, nshifts=10, outdir='.', outname='auto', pad=100, post_mortem=False, rescale=False, rescale_pad=1.0, rescale_size=99, save_all=False, seed=None, subset=0, unbalanced=False, weight_name='weight')
NumExpr defaulting to 8 threads.
chr1: 8
Traceback (most recent call last):
  File "/Users/tanlongzhi/anaconda2/envs/py3/bin/coolpup.py", line 10, in <module>
    sys.exit(main())
  File "/Users/tanlongzhi/anaconda2/envs/py3/lib/python3.7/site-packages/coolpuppy/__main__.py", line 535, in main
    pup, n = PU.pileupsWithControl(nproc)
  File "/Users/tanlongzhi/anaconda2/envs/py3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1160, in pileupsWithControl
    loops, nums, cov_starts, cov_ends, ns = list(zip(*mymap(f, self.chroms)))
  File "/Users/tanlongzhi/anaconda2/envs/py3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1131, in pileup_chrom
    mids=mids, chrom=chrom, expected=expected,
  File "/Users/tanlongzhi/anaconda2/envs/py3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 1002, in _do_pileups
    if stBin > endBin:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

Best,
Tan

**Comment by Phlya** [comment]
Hi Tan,

Glad you enjoy coolpuppy!

Apologies, this was cause by a small stupid bug in the recent versions, which didn't let analysis of chromosomes with single regions to work. Please try the new version from GitHub.

Cheers,
Ilya

**Comment by tanlongzhi** [comment]
Thanks a lot Ilya! I'll give it a try.

BTW, will there be a stranded BED option for piling up in certain directions (e.g. the direction of gene transcription)?

**Comment by Phlya** [comment]
Yeah I wanted to add that, but I am not sure about the best way to implement it at the moment. I wanted to implement generally arbitrary grouping of regions, but actually strands are a special case where on of them also needs to be flipped, so perhaps that can be added as a separate simple feature.

For now I just do two separate pileups for two strands, which you can average manually afterwards, actually, if you prefer - just flip one, and then average them with weights equal to how many regions were used in each pileup, which is saved in the header Let me know if you need help with that, should be a trivial function using numpy.

**Comment by tanlongzhi** [comment]
Thanks a lot for the detailed explanation! The two separate pileups makes sense; I'll try it out (I've been using the CLI only, but will learn the Python version for combining with Numpy).

Look forward to the new features!

Best,
Tan

**Comment by Phlya** [comment]
You can still run coolpuppy with CLI (I prefer that myself), just load the results into python.

There should be a function `coolpuppy.load_array_with_header` which should read in a file and output a dictionary with all metadata, and the pileup will be in `dict['data']`.

**Comment by tanlongzhi** [comment]
That's a wonderful tip!!

**Comment by Phlya** [comment]
No problem, hope that works, let me know if you have any issues!
