### ISSUE TITLE
importing numutils from cooltools

### ISSUE THREAD

**Issue by demmerle** [Phlya/coolpuppy#4]
Running: Python 3.7.1; conda 4.6.9; cooler 0.7; cooltools 0.1.0

Hi, really excited about coolpup.py but having some issues getting it going. Installs fine, but when I call the --help command I get some errors

`Traceback (most recent call last):
  File "/data/demmerlejt/conda/envs/02_coolpuptest/bin/coolpup.py", line 6, in <module>
    from coolpuppy.__main__ import main
  File "/data/demmerlejt/conda/envs/02_coolpuptest/lib/python3.7/site-packages/coolpuppy/__init__.py", line 1, in <module>
    from .coolpup import *
  File "/data/demmerlejt/conda/envs/02_coolpuptest/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 23, in <module>
    from cooltools import numutils
ImportError: cannot import name 'numutils' from 'cooltools' (/data/demmerlejt/conda/envs/02_coolpuptest/lib/python3.7/site-packages/cooltools/__init__.py)`

When I go look at the cooltools __init__.py file, there is no "numutils" in it. It reads only 
`from .consul import Consul
from .redshift import Redshift
from .slack import Slack`

However, in the cooltools guthub the equivalent file imports '.lib' and then imports numutils from .lib, which can be seen here https://github.com/mirnylab/cooltools/blob/master/cooltools/__init__.py

So, not sure why these are different, but should I change them manually, or am I installing something incorrectly? If so, any ideas on how to fix it? 

Also, I tried installing both the pip cooltools and via the https://github.com/mirnylab/cooltools/archive/master.zip link, and it didn't make a difference. 

Thanks in advance for your help, 
Justin

**Comment by Phlya** [comment]
Hi, I can have a more careful look at this tomorrow, but you definitely
want cooltools from mirnylab github - the ones on pypi are unrelated and
will hopefully be soon replaced by the right ones. Pleas make sure it's
properly installed from github, it should work then, let me know of it
doesn't!

Ilya

**Comment by Phlya** [comment]
Closing this, feel free to reopen if you still have a problem.
