### ISSUE TITLE
by_window together with local

### ISSUE THREAD

**Issue by Darlingfuer** [Phlya/coolpuppy#7]
Hi, I am trying to getting the local pileups for every single region just like what the "loop-ability" do. However, I found that "--by_window" is not compatible with "--local". Are there any other ways of saving all the single maps for local and rescaled local pileups?

**Comment by Phlya** [comment]
Hi, thank you for using coolpuppy! No, it's currently not possible, sorry, although I have considered adding this option. Coolpuppy is designed to be able to work with huge numbers of regions, and it's not really compatible with saving all individual windows... I might add this option in the future though.

And I just want to mention, loop-ability doesn't save all windows used for averaging, but generates a separate pileup for each interval against the rest of intervals in the same chromosome, so it wouldn't be exactly the same as saving all local regions.

A tool I have seen that can do this is this: https://github.com/agalitsyna/avTAD
I haven't tried it myself though.

**Comment by Darlingfuer** [comment]
Many thanks for the detailed explanation! This is an extremely helpful tool for a newbie like me!

**Comment by Phlya** [comment]
Thank you for your feedback, and glad coolpuppy is useful! Feel free to ask more questions.

I'm closing this issue.
