### ISSUE TITLE
plotpup.py

### ISSUE THREAD

**Issue by Kurotakid** [Phlya/coolpuppy#9]
Hi,
I'm a beginner of python. I'm testing the coolpup.py and plotpup.py programs with your test data (i.e. Scc1-KO.10000.cool, Scc1-control.10000.cool, and CH12_TADs_Rao.bed files). I successfully created Scc1KO_loop.txt and Ctrl_loop.txt files (please see attached files). However, when I performed the next command, I received an error message.

[coolpuppy-master/docs]$plotpup.py Ctrl_loop.txt Scc1KO_loop.txt --row_names Control,Scc1KO --enrichment 3 --output loops.png
Traceback (most recent call last):
  File "/home/usr/miniconda3/bin/plotpup.py", line 10, in <module>
    sys.exit(plotpuppy())
  File "/home/usr/miniconda3/lib/python3.6/site-packages/coolpuppy/__main__.py", line 524, in plotpuppy
    pups = np.asarray(pups+extra).reshape((n_rows, n_cols))
ValueError: cannot reshape array of size 882 into shape (2,1)

How can I resolve this problem?
Daisuke

[Ctrl_loop.txt](https://github.com/Phlya/coolpuppy/files/3667305/Ctrl_loop.txt)
[Scc1KO_loop.txt](https://github.com/Phlya/coolpuppy/files/3667306/Scc1KO_loop.txt)

**Comment by Phlya** [comment]
Hi, I think you using an old version (did I forget to update it on PyPI? sorry!), please try to install the latest one from github

`pip install https://github.com/Phlya/coolpuppy/archive/master.zip`

**Comment by Kurotakid** [comment]
Thank you so much! I could get the correct result.
I appreciated your help.
Daisuke

**Comment by Phlya** [comment]
Great, good to hear! Good luck, let me know if you have any more issues!
